version: "3.7"

services:
    database_gazin:
        image: postgres
        container_name: database_gazin
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=gazin
        volumes:
            - pgdata:/data/postgres
        network_mode: host
    app:
        build: .
        container_name: backend_gazin
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        network_mode: host

volumes:
    pgdata:
        driver: local
