version: "3.9"

services:
    database:
        image: postgres
        container_name: database_gazin
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=gazin
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: backend_gazin
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes:
    pgdata:
        driver: local
